# Generated by Django 5.2.4 on 2026-02-26 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_hostelmessmenu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelmaintenancerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_maintenance_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelmaintenancerequest',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelmaintenancerequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
