# Generated by Django 5.2.4 on 2026-02-26 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_hostelmaintenancerequest_approved_by_and_more'),
        ('students', '0008_studentpasswordresetrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending_warden', 'Pending Warden'), ('pending_parent', 'Pending Parent'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_warden', max_length=20)),
                ('warden_note', models.TextField(blank=True, null=True)),
                ('warden_action_on', models.DateTimeField(blank=True, null=True)),
                ('parent_note', models.TextField(blank=True, null=True)),
                ('parent_action_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_leave_parent_actions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_leave_requests', to='students.student')),
                ('warden_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_leave_warden_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
