# Generated by Django 5.2.4 on 2026-02-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('librarian', 'Librarian'), ('hostel_warden', 'Hostel Warden')], default='student', max_length=20),
        ),
    ]
