# Generated by Django 5.2.4 on 2026-01-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_roll_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['class_name', 'section'],
                'unique_together': {('class_name', 'section')},
            },
        ),
    ]
