# Generated by Django 5.2.4 on 2025-10-03 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('joining_date', models.DateField()),
                ('qualification', models.CharField(choices=[('B.A', 'Bachelor of Arts'), ('B.Sc', 'Bachelor of Science'), ('B.Ed', 'Bachelor of Education'), ('M.A', 'Master of Arts'), ('M.Sc', 'Master of Science'), ('M.Ed', 'Master of Education'), ('Ph.D', 'Doctor of Philosophy'), ('Other', 'Other')], max_length=20)),
                ('department', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('Social Studies', 'Social Studies'), ('Physical Education', 'Physical Education'), ('Computer Science', 'Computer Science'), ('Arts', 'Arts'), ('Music', 'Music'), ('Other', 'Other')], max_length=50)),
                ('designation', models.CharField(default='Teacher', max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['employee_id'],
            },
        ),
    ]
