# Generated by Django 5.2.4 on 2026-01-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_classsection'),
        ('teachers', '0002_add_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_sections',
            field=models.ManyToManyField(blank=True, help_text='Class-section combinations this teacher is responsible for', related_name='teachers', to='students.classsection'),
        ),
    ]
