# Generated by Django 5.2.4 on 2026-02-25 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('objectives', models.TextField(blank=True)),
                ('materials', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='timetable.classschedule')),
            ],
            options={
                'ordering': ['-lesson_date', 'schedule__class_name', 'schedule__section', 'schedule__period'],
                'unique_together': {('schedule', 'lesson_date')},
            },
        ),
    ]
