# Generated by Django 5.2.4 on 2026-01-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_section',
            field=models.CharField(blank=True, help_text="Optional section when assigning to a class (e.g., 'A')", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='feedback',
            field=models.TextField(blank=True, help_text='Teacher feedback on submission', null=True),
        ),
    ]
