# Generated by Django 5.2.4 on 2026-02-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('students', '0007_cv_approval_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='notes.note')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_views', to='students.student')),
            ],
            options={
                'ordering': ['-last_viewed_at'],
                'unique_together': {('note', 'student')},
            },
        ),
    ]
